[package]
name = "cursive_tree_view_nj"
version = "0.1.0"
authors = ["Ivo Wetzel <ivo.wetzel@googlemail.com>", "Google LLC <njskalski@google.com>"]
description = "A tree view implementation for cursive. Fork of https://github.com/BonsaiDen/cursive_tree_view.git updated by NJ Skalski"
repository = "https://github.com/BonsaiDen/cursive_tree_view.git"
readme = "README.md"
keywords = ["cursive", "ncurses", "TUI", "UI", "tree"]
categories = ["command-line-interface", "gui"]
license = "Apache-2.0"

[dependencies]
debug_stub_derive = "0.3.0"
cursive = { version = "0.9", default-features = false }

[features]
default = ["ncurses-backend"]
ncurses-backend = ["cursive/ncurses-backend"]
pancurses-backend = ["cursive/pancurses-backend"]
termion-backend = ["cursive/termion-backend"]
blt-backend = ["cursive/blt-backend"]
